// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AmbientDirector.Api.Data;

#nullable disable

namespace AmbientDirector.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709175717_PerLightScenesAndEffects")]
    partial class PerLightScenesAndEffects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AmbientDirector.Api.Data.LightingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LightingConfigs");
                });

            modelBuilder.Entity("AmbientDirector.Api.Models.Scene", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SoundEffects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("AmbientDirector.Api.Data.LightingConfig", b =>
                {
                    b.OwnsOne("AmbientDirector.Api.Data.HueConfig", "Hue", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("AppKey")
                                .IsRequired();

                            b1.Property<string>("BridgeIp")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("LightIds")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Hue")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsMany("AmbientDirector.Api.Data.RegisteredLight", "Lights", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("HueId");

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Provider")
                                .IsRequired();

                            b1.HasKey("LightingConfigId", "__synthesizedOrdinal");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Lights")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsOne("AmbientDirector.Api.Data.TuyaConfig", "Tuya", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("DeviceId")
                                .IsRequired();

                            b1.Property<string>("DpProfile")
                                .IsRequired();

                            b1.Property<string>("Ip")
                                .IsRequired();

                            b1.Property<string>("LocalKey")
                                .IsRequired();

                            b1.Property<string>("ProtocolVersion")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Tuya")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.Navigation("Hue")
                        .IsRequired();

                    b.Navigation("Lights");

                    b.Navigation("Tuya")
                        .IsRequired();
                });

            modelBuilder.Entity("AmbientDirector.Api.Models.Scene", b =>
                {
                    b.OwnsOne("AmbientDirector.Api.Models.LightSettings", "Light", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Light")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsOne("AmbientDirector.Api.Models.MusicSettings", "Music", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<bool>("Pause");

                            b1.Property<string>("PlayId");

                            b1.Property<double?>("Volume");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Music")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsMany("AmbientDirector.Api.Models.SceneLight", "Lights", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<string>("LightKey")
                                .IsRequired();

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("SceneId", "__synthesizedOrdinal");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Lights")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");

                            b1.OwnsOne("AmbientDirector.Api.Models.LightEffect", "Effect", b2 =>
                                {
                                    b2.Property<string>("SceneLightSceneId");

                                    b2.Property<int>("SceneLight__synthesizedOrdinal");

                                    b2.PrimitiveCollection<string>("Colors")
                                        .IsRequired();

                                    b2.Property<int>("Intensity");

                                    b2.Property<int>("Speed");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("SceneLightSceneId", "SceneLight__synthesizedOrdinal");

                                    b2.ToTable("Scenes");

                                    b2.WithOwner()
                                        .HasForeignKey("SceneLightSceneId", "SceneLight__synthesizedOrdinal");
                                });

                            b1.Navigation("Effect");
                        });

                    b.Navigation("Light");

                    b.Navigation("Lights");

                    b.Navigation("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
