// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgSceneMaker.Api.Data;

#nullable disable

namespace RpgSceneMaker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710122150_EventTimelineAndSoundDuration")]
    partial class EventTimelineAndSoundDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RpgSceneMaker.Api.Data.LightingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LightingConfigs");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Data.SpotifyConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredDeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredDeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpotifyConfigs");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.GameEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SoundEffects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Scene", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SoundEffects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Screen", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Sound", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Data.LightingConfig", b =>
                {
                    b.OwnsOne("RpgSceneMaker.Api.Data.HueConfig", "Hue", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("AppKey")
                                .IsRequired();

                            b1.Property<string>("BridgeIp")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("LightIds")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Hue")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Models.LightSettings", "DefaultLight", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("DefaultLight")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsMany("RpgSceneMaker.Api.Data.RegisteredLight", "Lights", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("HueId");

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Provider")
                                .IsRequired();

                            b1.HasKey("LightingConfigId", "__synthesizedOrdinal");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Lights")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Data.TuyaConfig", "Tuya", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("DeviceId")
                                .IsRequired();

                            b1.Property<string>("DpProfile")
                                .IsRequired();

                            b1.Property<string>("Ip")
                                .IsRequired();

                            b1.Property<string>("LocalKey")
                                .IsRequired();

                            b1.Property<string>("ProtocolVersion")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Tuya")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.Navigation("DefaultLight");

                    b.Navigation("Hue")
                        .IsRequired();

                    b.Navigation("Lights");

                    b.Navigation("Tuya")
                        .IsRequired();
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.GameEvent", b =>
                {
                    b.OwnsOne("RpgSceneMaker.Api.Models.EventFlash", "Flash", b1 =>
                        {
                            b1.Property<string>("GameEventId");

                            b1.Property<int>("Brightness");

                            b1.Property<string>("Color")
                                .IsRequired();

                            b1.Property<int>("DurationMs");

                            b1.HasKey("GameEventId");

                            b1.ToTable("Events");

                            b1
                                .ToJson("Flash")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("GameEventId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Models.EventTimeline", "Timeline", b1 =>
                        {
                            b1.Property<string>("GameEventId");

                            b1.HasKey("GameEventId");

                            b1.ToTable("Events");

                            b1
                                .ToJson("Timeline")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("GameEventId");

                            b1.OwnsMany("RpgSceneMaker.Api.Models.TimelineLightClip", "Lights", b2 =>
                                {
                                    b2.Property<string>("EventTimelineGameEventId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int?>("Brightness");

                                    b2.Property<string>("Color");

                                    b2.Property<int>("DurationMs");

                                    b2.Property<string>("LightKey");

                                    b2.Property<bool?>("Power");

                                    b2.Property<int>("StartMs");

                                    b2.Property<int?>("Temperature");

                                    b2.HasKey("EventTimelineGameEventId", "__synthesizedOrdinal");

                                    b2.ToTable("Events");

                                    b2.WithOwner()
                                        .HasForeignKey("EventTimelineGameEventId");

                                    b2.OwnsOne("RpgSceneMaker.Api.Models.LightEffect", "Effect", b3 =>
                                        {
                                            b3.Property<string>("TimelineLightClipEventTimelineGameEventId");

                                            b3.Property<int>("TimelineLightClip__synthesizedOrdinal");

                                            b3.PrimitiveCollection<string>("Colors")
                                                .IsRequired();

                                            b3.Property<int>("Intensity");

                                            b3.Property<int>("Speed");

                                            b3.Property<string>("Type")
                                                .IsRequired();

                                            b3.HasKey("TimelineLightClipEventTimelineGameEventId", "TimelineLightClip__synthesizedOrdinal");

                                            b3.ToTable("Events");

                                            b3.WithOwner()
                                                .HasForeignKey("TimelineLightClipEventTimelineGameEventId", "TimelineLightClip__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Effect");
                                });

                            b1.OwnsMany("RpgSceneMaker.Api.Models.TimelineSoundClip", "Sounds", b2 =>
                                {
                                    b2.Property<string>("EventTimelineGameEventId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int?>("DurationMs");

                                    b2.Property<string>("SoundId")
                                        .IsRequired();

                                    b2.Property<int>("StartMs");

                                    b2.Property<double?>("Volume");

                                    b2.HasKey("EventTimelineGameEventId", "__synthesizedOrdinal");

                                    b2.ToTable("Events");

                                    b2.WithOwner()
                                        .HasForeignKey("EventTimelineGameEventId");
                                });

                            b1.Navigation("Lights");

                            b1.Navigation("Sounds");
                        });

                    b.Navigation("Flash");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Scene", b =>
                {
                    b.OwnsOne("RpgSceneMaker.Api.Models.MusicSettings", "Music", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<bool>("Pause");

                            b1.Property<string>("PlayId");

                            b1.Property<double?>("Volume");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Music")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Models.LightSettings", "Light", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Light")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsMany("RpgSceneMaker.Api.Models.SceneLight", "Lights", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<string>("LightKey")
                                .IsRequired();

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("SceneId", "__synthesizedOrdinal");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Lights")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");

                            b1.OwnsOne("RpgSceneMaker.Api.Models.LightEffect", "Effect", b2 =>
                                {
                                    b2.Property<string>("SceneLightSceneId");

                                    b2.Property<int>("SceneLight__synthesizedOrdinal");

                                    b2.PrimitiveCollection<string>("Colors")
                                        .IsRequired();

                                    b2.Property<int>("Intensity");

                                    b2.Property<int>("Speed");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("SceneLightSceneId", "SceneLight__synthesizedOrdinal");

                                    b2.ToTable("Scenes");

                                    b2.WithOwner()
                                        .HasForeignKey("SceneLightSceneId", "SceneLight__synthesizedOrdinal");
                                });

                            b1.Navigation("Effect");
                        });

                    b.Navigation("Light");

                    b.Navigation("Lights");

                    b.Navigation("Music");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Screen", b =>
                {
                    b.OwnsMany("RpgSceneMaker.Api.Models.ScreenTile", "Tiles", b1 =>
                        {
                            b1.Property<string>("ScreenId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Kind")
                                .IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<string>("Ref")
                                .IsRequired();

                            b1.HasKey("ScreenId", "__synthesizedOrdinal");

                            b1.ToTable("Screens");

                            b1
                                .ToJson("Tiles")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ScreenId");
                        });

                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
