// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgSceneMaker.Api.Data;

#nullable disable

namespace RpgSceneMaker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RpgSceneMaker.Api.Data.LightingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LightingConfigs");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Scene", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SoundEffects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Data.LightingConfig", b =>
                {
                    b.OwnsOne("RpgSceneMaker.Api.Data.HueConfig", "Hue", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("AppKey")
                                .IsRequired();

                            b1.Property<string>("BridgeIp")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("LightIds")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Hue")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Data.TuyaConfig", "Tuya", b1 =>
                        {
                            b1.Property<int>("LightingConfigId");

                            b1.Property<string>("DeviceId")
                                .IsRequired();

                            b1.Property<string>("DpProfile")
                                .IsRequired();

                            b1.Property<string>("Ip")
                                .IsRequired();

                            b1.Property<string>("LocalKey")
                                .IsRequired();

                            b1.Property<string>("ProtocolVersion")
                                .IsRequired();

                            b1.HasKey("LightingConfigId");

                            b1.ToTable("LightingConfigs");

                            b1
                                .ToJson("Tuya")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("LightingConfigId");
                        });

                    b.Navigation("Hue")
                        .IsRequired();

                    b.Navigation("Tuya")
                        .IsRequired();
                });

            modelBuilder.Entity("RpgSceneMaker.Api.Models.Scene", b =>
                {
                    b.OwnsOne("RpgSceneMaker.Api.Models.LightSettings", "Light", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<int?>("Brightness");

                            b1.Property<string>("Color");

                            b1.Property<bool?>("Power");

                            b1.Property<int?>("Temperature");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Light")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsOne("RpgSceneMaker.Api.Models.MusicSettings", "Music", b1 =>
                        {
                            b1.Property<string>("SceneId");

                            b1.Property<bool>("Pause");

                            b1.Property<string>("PlayId");

                            b1.Property<double?>("Volume");

                            b1.HasKey("SceneId");

                            b1.ToTable("Scenes");

                            b1
                                .ToJson("Music")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.Navigation("Light");

                    b.Navigation("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
